##
## EPITECH PROJECT, 2021
## makefile infin_add
## File description:
## Makefile
##

SRC	=	zappy_ai	\

CFLAGS	=	-std=gnu17 -Wall -Wextra

all:    $(NAME)


$(NAME):
	@chmod 777 $(SRC)
	@echo -e "\e[92;5m       ====Bien joué bg====      \e[0m"

clean:

fclean:
	@chmod 775 $(SRC)

re: fclean all
